version: "3.11"

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: starterPasswordRoot
      MYSQL_DATABASE: starterdb
      MYSQL_USER: starterUser
      MYSQL_PASSWORD: starterPassword
    ports:
      - "3307:3306"
      -
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

    volumes:
      - .:/src

    command: ["redis-server"]


  webapp:
    restart: always
    volumes:
      - static:/static
    build:
      context: starter_expert
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

    command: 'sh -c "cd src && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn starter.wsgi:application --bind 0.0.0.0:8000"'

  nginx:
    build:
      context: starter_expert/nginx

    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - webapp


  worker:
    restart: always
    build:
      context: starter_expert
    volumes:
      - .:/src

    depends_on:
      - db
    command: "celery --workdir=./src -A starter worker -l info"

  celery-beat:
    restart: always
    build:
      context: starter_expert

    volumes:
      - .:/src

    depends_on:
      - db
      -
    command: "celery --workdir=./src -A starter beat -l info"




volumes:
  static:
