# Generated by Django 4.2.4 on 2023-08-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет по индексатору',
                'verbose_name_plural': 'Индексатор, Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('normalized_keywords', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Топ запрос',
                'verbose_name_plural': 'Топ запросы',
            },
        ),
        migrations.CreateModel(
            name='Seo_collector_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NmidToBeReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('seo_collector_keywords', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wb.seo_collector_report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='IndexerReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('req_depth', models.IntegerField()),
                ('existence', models.BooleanField()),
                ('place', models.IntegerField(default=None, null=True)),
                ('spot_req_depth', models.CharField(default=None, max_length=255, null=True)),
                ('ad_spots', models.IntegerField(default=None, null=True)),
                ('ad_place', models.IntegerField(default=None, null=True)),
                ('product_id', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.indexerreport')),
            ],
            options={
                'verbose_name': 'Данные по отчету',
                'verbose_name_plural': 'Данные по отчетам',
            },
        ),
    ]
