# Generated by Django 4.2.4 on 2023-10-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.TextField()),
                ('useless_field', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='IndexerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
                ('product_name', models.CharField(default='', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('quick_indexation', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('date_of_readiness', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Отчет по индексатору',
                'verbose_name_plural': 'Индексатор, Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('normalized_keywords', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Топ запрос',
                'verbose_name_plural': 'Топ запросы',
            },
        ),
        migrations.CreateModel(
            name='SeoCollectorPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('req_depth', models.IntegerField()),
                ('priority_cat', models.CharField(default='', max_length=255)),
                ('ready', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
            },
        ),
        migrations.CreateModel(
            name='SeoCollectorPhraseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('priority_cat', models.CharField(max_length=255)),
                ('standard', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(default=None, null=True)),
                ('depth', models.IntegerField(default=None, null=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.seocollectorphrase')),
            ],
            options={
                'verbose_name': 'Данные по отчету Сео',
                'verbose_name_plural': 'Данные по отчетам Сео',
            },
        ),
        migrations.CreateModel(
            name='NmidToBeReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
                ('url', models.URLField()),
                ('phrase', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wb.seocollectorphrase')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='IndexerReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(null=True)),
                ('req_depth', models.IntegerField()),
                ('existence', models.BooleanField()),
                ('place', models.IntegerField(default=None, null=True)),
                ('spot_req_depth', models.CharField(default=None, max_length=255, null=True)),
                ('ad_spots', models.IntegerField(default=None, null=True)),
                ('ad_place', models.IntegerField(default=None, null=True)),
                ('product_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.indexerreport')),
            ],
            options={
                'verbose_name': 'Данные по отчету Индексация',
                'verbose_name_plural': 'Данные по отчетам Индексация',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('req_depth', models.IntegerField()),
                ('frequency', models.IntegerField(default=None, null=True)),
                ('priority_cat', models.CharField(default='', max_length=255)),
                ('ready', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статистика топовой фразы',
                'verbose_name_plural': 'Статистика топовых фраз',
            },
        ),
    ]
