# Generated by Django 4.2.4 on 2023-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexerreportdata',
            name='priority_cat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
