# Generated by Django 4.2.4 on 2023-10-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexerreport',
            old_name='product_name',
            new_name='name',
        ),
    ]
