# Generated by Django 4.2.4 on 2023-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('normalized_keywords', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Топ запрос',
                'verbose_name_plural': 'Топ запросы',
            },
        ),
    ]
