# Generated by Django 4.2.4 on 2023-10-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexerreport',
            name='product_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
