# Generated by Django 4.2.4 on 2023-08-25 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0002_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoCollectorPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('req_depth', models.IntegerField()),
                ('ready', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
            },
        ),
        migrations.CreateModel(
            name='SeoCollectorPhraseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('priority_cat', models.CharField(max_length=255)),
                ('standard', models.BooleanField(default=False)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.seocollectorphrase')),
            ],
            options={
                'verbose_name': 'Данные по отчету',
                'verbose_name_plural': 'Данные по отчету',
            },
        ),
    ]
