# Generated by Django 4.2.4 on 2023-08-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0003_seocollectorphrase_seocollectorphrasedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocollectorphrase',
            name='priority_cat',
            field=models.CharField(default='', max_length=255),
        ),
    ]
