# Generated by Django 4.2.4 on 2023-09-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0004_seocollectorphrase_priority_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexerreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nmidtobereported',
            name='user',
        ),
        migrations.AddField(
            model_name='nmidtobereported',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wb.seocollectorphrase'),
        ),
        migrations.AlterField(
            model_name='seocollectorphrase',
            name='phrase',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
