# Generated by Django 4.2.4 on 2023-10-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0004_indexerreportdata_quick_indexation'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='second_top_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='phrase',
            name='third_top_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='phrase',
            name='top_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='phrase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
