# Generated by Django 4.2.4 on 2023-09-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0005_remove_indexerreport_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmidtobereported',
            name='phrase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wb.seocollectorphrase'),
        ),
    ]
