# Generated by Django 4.2.4 on 2023-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0006_alter_nmidtobereported_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexerreportdata',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
    ]
