# Generated by Django 4.2.4 on 2023-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0008_nmidtobereported_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocollectorphrasedata',
            name='depth',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='seocollectorphrasedata',
            name='frequency',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
