# Generated by Django 4.2.4 on 2023-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0009_seocollectorphrasedata_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexerreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
