# Generated by Django 4.2.4 on 2023-09-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0010_alter_indexerreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexerreportdata',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
