# Generated by Django 4.2.4 on 2023-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0013_alter_indexerreportdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='useless_field',
            field=models.BooleanField(default=False),
        ),
    ]
