# Generated by Django 4.2.4 on 2023-10-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0014_cabinet_useless_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexerreport',
            name='product_name',
        ),
    ]
