# Generated by Django 4.2.4 on 2023-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0015_remove_indexerreport_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexerreport',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
