# Generated by Django 4.2.1 on 2023-08-23 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCreateReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OzonIndexerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
                ('date_create_reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.datecreatereports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет по индексатору',
                'verbose_name_plural': 'Индексатор, Отчеты',
            },
        ),
        migrations.CreateModel(
            name='OzonNmidToBeReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OzonIndexerReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(max_length=255, verbose_name='Поисковой запрос')),
                ('frequency', models.IntegerField(verbose_name='Насколько популярен запрос')),
                ('req_depth', models.IntegerField(verbose_name='Количество товара')),
                ('existence', models.BooleanField(verbose_name='Есть в топовой выдаче')),
                ('place', models.IntegerField(default=None, null=True)),
                ('spot_req_depth', models.CharField(default=None, max_length=255, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ozon.ozonindexerreport')),
            ],
            options={
                'verbose_name': 'Данные по отчету',
                'verbose_name_plural': 'Данные по отчетам',
            },
        ),
    ]
